# fly.toml app configuration file generated for my-node-server on 2023-12-26T19:45:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-node-server"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
